# Generated by Django 5.2.9 on 2025-12-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False)),
            ],
        ),
    ]
