let numero1 = 1;
console.log(typeof numero1);
let numero2 = 1.03;
console.log(typeof numero2);
let booleano = true;
console.log(typeof booleano);
let cadena = "hola";
console.log(typeof cadena);
let nulo = null;
console.log(typeof nulo);
let indefinido;
console.log(typeof indefinido);
let objeto = {a:1};
console.log(typeof objeto);